### ISSUE TITLE
When the android version of the app will be released?

### ISSUE THREAD

**Issue by ivankarmanow** [Kolotushka1/Java-easy-chat#1]
When the android version of the app will be released?
![Bhaa0jGvMYE](https://github.com/Kolotushka1/Java-easy-chat/assets/61072422/c0fdf8de-50aa-4739-8c0f-bc0cb0a45b53)

**Comment by ivankarmanow** [comment]
@Kolotushka1, why is it taking so long to get an answer?

**Comment by Kolotushka1** [comment]
Hello, my dear viewer, I guess that my app is kinda simple, so I will not be able to make an Android app, because it's kinda hard for this type of work, sorry...
